src/Entity/Workout.php
<?php
/**
 * Created by PhpStorm.
 * User: langur
 * Date: 13.03.2018
 * Time: 20:31
 */

namespace App\Entity;

use App\Utils\Date;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Workout
 * @package App\Entity
 *
 * @ORM\Entity(repositoryClass="App\Repository\WorkoutRepository")
 */
class Workout
{
    const TYPE_RUN = 1;
    const TYPE_RIDE = 2;

    private static $types = [
        self::TYPE_RUN  => 'Run',
        self::TYPE_RIDE => 'Ride'
    ];

    /**
     * @var string
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column("string")
     */
    protected $id;

    /**
     * Type of workout
     *
     * @var int
     * @ORM\Column(type="smallint")
     */
    protected $type;

    /**
     * Distance in km
     *
     * @var int
     * @ORM\Column(type="integer")
     */
    protected $distance;

    /**
     * Starting time
     *
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $startTime;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $finishTime;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $private = false;

    /**
     * @return null|string
     */
    public function getTypeString(): ?string
    {
        return isset(static::$types[$this->type]) ? static::$types[$this->type] : null;
    }

    /**
     * @return array
     */
    public static function getTypes(): array
    {
        return static::$types;
    }

    /**
     * Return string representation of duration
     * @return null|string
     */
    public function getDuration(): ?string
    {
        if($this->startTime === null || $this->finishTime === null) {
            return null;
        }
        return Date::duration($this->startTime, $this->finishTime);
    }

//GENERATED
    /**
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string $id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * @param int $type
     */
    public function setType(int $type): void
    {
        $this->type = $type;
    }

    /**
     * @return int
     */
    public function getDistance(): ?int
    {
        return $this->distance;
    }

    /**
     * @param int $distance
     */
    public function setDistance(int $distance): void
    {
        $this->distance = $distance;
    }

    /**
     * @return \DateTime
     */
    public function getStartTime(): ?\DateTime
    {
        return $this->startTime;
    }

    /**
     * @param \DateTime $startTime
     */
    public function setStartTime(\DateTime $startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * @return \DateTime
     */
    public function getFinishTime(): ?\DateTime
    {
        return $this->finishTime;
    }

    /**
     * @param \DateTime $finishTime
     */
    public function setFinishTime(\DateTime $finishTime): void
    {
        $this->finishTime = $finishTime;
    }

    /**
     * @return bool
     */
    public function isPrivate(): ?bool
    {
        return $this->private;
    }

    /**
     * @param bool $private
     */
    public function setPrivate(bool $private): void
    {
        $this->private = $private;
    }


}

src/Form/WorkoutType.php
<?php
/**
 * Created by PhpStorm.
 * User: langur
 * Date: 14.03.2018
 * Time: 15:17
 */

namespace App\Form;

use App\Entity\Post;
use App\Entity\Workout;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class WorkoutType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type', ChoiceType::class, [
                'attr'    => ['autofocus' => true],
                'label'   => 'label.type',
                'choices' => array_flip(Workout::getTypes())
            ])
            ->add('distance', null, [
                'attr'  => ['autofocus' => true],
                'label' => 'label.distance',
            ])
            ->add('startTime', null, [
                'label' => 'label.startTime',
            ])
            ->add('finishTime', null, [
                'attr'  => ['rows' => 20],
                'label' => 'label.finishTime',
            ])
            ->add('private', null, [
                'label'    => 'label.private',
                'required' => false,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'label.save'
            ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Workout::class,
        ]);
    }
}

src/Controller/WorkoutController.php
<?php
/**
 * Created by PhpStorm.
 * User: langur
 * Date: 13.03.2018
 * Time: 20:31
 */

namespace App\Controller;


use App\Entity\Workout;
use App\Form\WorkoutType;
use App\Repository\WorkoutRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class WorkoutController used to manage Workouts
 *
 * @package App\Controller
 */
class WorkoutController extends Controller
{

    /**
     * @Route("/")
     * @Method("GET")
     *
     * @param WorkoutRepository $repo
     * @return Response
     */
    public function index(WorkoutRepository $repo): Response
    {
        return $this->render('workouts/index.html.twig', ['workouts' => $repo->findAll()]);
    }

    /**
     * @Route("/add")
     * @Method({"GET", "POST"})
     *
     * @param Request $request
     * @return Response
     */
    public function add(Request $request): Response
    {
        $workout = new Workout();
        $form = $this->createForm(WorkoutType::class, $workout);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($workout);
            $em->flush();
            $this->addFlash('success', 'workout.created');
            return $this->redirectToRoute('app_workout_index');
        }
        return $this->render('workouts/add.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/edit/{id}")
     * @Method({"GET", "POST"})
     *
     * @param Request $request
     * @param Workout $workout
     * @return Response
     */
    public function edit(Request $request, Workout $workout): Response
    {
        $form = $this->createForm(WorkoutType::class, $workout);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($workout);
            $em->flush();
            $this->addFlash('success', 'workout.edited');
            return $this->redirectToRoute('app_workout_index');
        }
        return $this->render('workouts/edit.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/delete/{id}")
     * @Method({"GET", "POST"})
     *
     * @param Workout $workout
     * @return Response
     */
    public function delete(Workout $workout): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($workout);
        $em->flush();
        $this->addFlash('success', 'workout.deleted');
        return $this->redirectToRoute('app_workout_index');
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('build/css/app.css') }}">
        {% endblock %}
    </head>
    <body>
        <div class="container">
            <h1 class="page-header">{% block h1 %}{% endblock %}</h1>

            <div class="messages">
                {% for type, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="alert alert-dismissible alert-{{ type }} fade in" role="alert">
                            {{ message|trans }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>

            {% block body %}{% endblock %}
        </div>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/workouts/add.html.twig
{% extends 'base.html.twig' %}

{% block h1 'New workout' %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/workouts/edit.html.twig
{% extends 'base.html.twig' %}

{% block h1 'Edit workout' %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/workouts/index.html.twig
{% extends 'base.html.twig' %}

{% block h1 'Workouts' %}

{% block body %}

    <a href="{{ path('app_workout_add') }}" id="btn-add-workout" class="btn btn-success">Add</a>
    <table class="table table-striped">
        <tr>
            <th>{{ 'label.type'|trans }}</th>
            <th>{{ 'label.distance'|trans }}</th>
            <th>{{ 'label.startTime'|trans }}</th>
            <th>{{ 'label.finishTime'|trans }}</th>
            <th>{{ 'label.duration'|trans }}</th>
            <th>{{ 'label.actions'|trans }}</th>
        </tr>
        {% for workout in workouts %}
            <tr>
                <td>{{ workout.typeString }}</td>
                <td>{{ workout.distance }}</td>
                <td>{{ workout.startTime|date }}</td>
                <td>{{ workout.finishTime|date }}</td>
                <td>{{ workout.duration }}</td>
                <td>
                    <a href="{{ path('app_workout_edit', {'id': workout.id}) }}" class="btn btn-warning">Edit</a>
                    <a href="{{ path('app_workout_delete', {'id': workout.id}) }}" class="btn btn-danger"
                       onclick="return confirm('Are you sure you want to delete this item?')">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}